### ISSUE TITLE
semicolon separated expressions

### ISSUE THREAD

**Issue by fjaifi** [patmok/unparse#2]
"a:10;b:10;a+b" produces "\";\"[(a :10);(b :10);(a+b)]"
I think it should be fairly easy to reconstruct the original format (there's also the case when there's a semicolon at the end)

**Comment by patmok** [comment]
yes it seems fairly easy to get the original format

but seeing as both expressions generate the same parse tree, neither is wrong?

**Comment by fjaifi** [comment]
I agree it is technically correct, though I would still argue that it is a big benefit that output be more readable especially when it is doable.
