### ISSUE TITLE
hand crafted parse trees

### ISSUE THREAD

**Issue by fjaifi** [patmok/unparse#4]
This is a valid parse tree, which represents a function that is called with a dictionary as its argument:
q)0N!eval  ({x};(enlist`x)!enlist`x)
(,`x)!,`x
x| x

q).unparse.unparse ({x};(enlist`x)!enlist`x)
"{x}[(,`x)!,`x]"

q)parse .unparse.unparse ({x};(enlist`x)!enlist`x)
k){$["\"=*x;(system;1_x);-5!x]}
',
!
-5
"{x}[(,`x)!,`x]"

**Comment by patmok** [comment]
Hmm, is there an expression e such that:

({x};reverse 1 2 3)~parse e

Am not sure there is one, I guess we can only unparse a strict parse tree. By strict I mean a parse tree that can be outputted by the parse function. A parse tree in the loose sense would be one that you can use eval to evaluate?

**Comment by fjaifi** [comment]
The sample expression i used is artificial to demonstrate the issue. My use case involves generating a parse tree by hand which then gets fed to an API that expects the expression as a string (will be parsed and evaluated), so I'm using unparse for that part. My benchmark is parse trees that can be evaluated.

**Comment by patmok** [comment]
I think not all parse trees have a string counter part, are you able to generate strict parse tree instead?

If its indeed true that some parse trees have no counter part, unparse could maybe throw an error since the output is undefined?

**Comment by fjaifi** [comment]
Your point make sense, I'll close the issue.
For reference, the concrete example is: given a parse tree n (which represents a select statement), I'm trying to generate a parse tree which is a function call that takes the where/by/aggr sections as arguments: (`f;n[2];n[3];n[4]).

**Comment by patmok** [comment]
qsql is a special case (see sql and sql0 functions)

q)parse"select a,b by c from t where i<5"
?
`t
,,(<;`i;5)
(,`c)!,`c
`a`b!`a`b

I would say the individual constraints and values of the group by and aggregates are strict parse trees (see sqla/sqlb/sqlc - they all call unparse)

If you have access to the API, my suggestion would be to do a type check on the input. If it's a string then do the usual parse and eval. If not, just do an eval. Generating (`f;n[2];n[3];n[4]) should be straight forward given n, without unparse.

I'll let you know if I think of something better
