### ISSUE TITLE
Does not handle functional selects etc.

### ISSUE THREAD

**Issue by semitrivial** [patmok/unparse#5]
`.unparse.unparse parse "?[t;();0b;(enlist c)!enlist c]"`

Returns this gibberish:

`"select ! from t"`

**Comment by patmok** [comment]
i see, sql function is incorrectly flagging the parse tree. i'll make sql more strict:

-sql:{$[proj f:first x;0b;not any(?;!)~:f;0b;5>count x;0b;proj x 2;0b;x~();1b;not enlist~first x 2]};
+sql:{$[proj f:first x;0b;not any(?;!)~:f;0b;5>count x;0b;proj x 2;0b;((1=count x4)&0h=type x4)|(99h=type x4)|(()~x4)|(`$())~x4:x 4;not enlist~first x 2;0b]};

thanks for reporting

**Comment by patmok** [comment]
fixed with the above
