### ISSUE TITLE
Doesn't handle linebreaks

### ISSUE THREAD

**Issue by semitrivial** [patmok/unparse#7]
`.unparse.unparse parse "tbl:select\n  from tbl\n  where i>0"`

Returns:
`"(tbl :select x:-38 from tbl[-38] where (i>0))"`

**Comment by patmok** [comment]
are you on windows?

**Comment by semitrivial** [comment]
Mac here at home.  Have windows and linux at work... I will check this bug on those systems when I go in tomorrow

**Comment by semitrivial** [comment]
Ok I tried it on different systems.  It's not an OS thing; it's a version thing.  Kdb 3.3's built-in parse function doesn't handle linebreaks (so not really unparse's fault).  In kdb 3.4 both parse and unparse handle linebreaks
