### ISSUE TITLE
Redundant ( ) brackets

### ISSUE THREAD

**Issue by danielkrizian** [patmok/unparse#8]
Excellent utility, hat down!

Tiny suggestion for improvement: removing redundant ( ) brackets would improve readability. Simplest example:

    q).unparse.unparse parse"a+b*c"
    "(a+(b*c))"

Perhaps brackets can be stripped in the post-processing stage on the resulting string?

_Side note:_ AFAIK q syntax doesn't have special operator precedence rules (dictionary), as it is parsed left-of-right. If it does, maybe in one of its built-in namespaces?

_Side note 2:_ Although not very relevant, here is an implementation of operator precedence logic, in inverse direction though: DSL string -> q tree https://github.com/josepablocam/posfixcalc/blob/master/posfixcalc.q#L3

**Comment by patmok** [comment]
Thanks for this Daniel

Tried adjusting `dinfix` to not call `dwrap""`, ends up failing a test case:


```
q).unparse.unparse parse "(1+2)*3"

"1+2*3"
```

I think you are right, might need to be a post processing of some sort, hmmm

For the above example if we want to remove brackets, we can return

`3*1+2`

This will give the same answer as `(1+2)*3` but it then means the parse tree would not match:

```
q)parse "(1+2)*3"
*
(+;1;2)
3
q)parse "3*1+2"
*
3
(+;1;2)

```

Thinking about this, I think this can be solved without post processing, but use a look back while we are adding the brackets in `dinfix`

**Comment by patmok** [comment]
```
q)\l testcases.q
q)\l t2.q
q)where not .unparse.test[]
q).unparse.unparse parse"a+b*c"
"a+b*c"
q).unparse.unparse parse"(a+b)*c"
"(a+b)*c"
q).unparse.unparse parse"a+(b*c)"
"a+b*c"
q).unparse.unparse parse"f[a;b]*c"
"f[a;b]*c"
q).unparse.unparse parse"f[a]*b"
"f[a]*b"
q).unparse.unparse parse"(f[a])*b"
"f[a]*b"
q).unparse.unparse parse"reverse[a]*b"
"(reverse a)*b"
```

I think I got it (see latest master), thoughts?

**Comment by danielkrizian** [comment]
Wow, that was quick! 👍 

Just one thing:

    q).unparse.unparse parse"f[a]*b"
    "f[a]*b"
    q).unparse.unparse parse"reverse[a]*b"
    "(reverse a)*b"
    
Note the last output instead of expected (and terser by one character! lol ) `"reverse[a]*b"`. This preference for `()` over `[]` seems to be the behaviour just for the built-in functions (`.q` namespace). User-defined functions unparse to square brackets `[]` as expected.

**Comment by patmok** [comment]
```
q).unparse.unparse parse"f[a]*b"
"f[a]*b"
q).unparse.unparse parse"reverse[a]*b"
"reverse[a]*b"
q).unparse.unparse parse"f each x"
"f each x"
```

Tidied it up now, nicer output with `each`, it's no longer prefix which I think is easier to read

**Comment by patmok** [comment]
just added a fix for handling ternary operators
